### ISSUE TITLE
failure with large dstat log files

### ISSUE THREAD

**Issue by halcyondude** [Dabz/dstat_graph#2]
I've noticed this when using large files (2+ hour data collection), which is my common use case. Loading the attached file, then selecting the entire time range causes an "oh snap" in chrome, or an exception in firefox.  I've also noticed this behavior when bouncing around with smaller ranges. 

I'm somewhat new to front-end development and d3, but this is giving me an excuse to dive in!

If you have any tips on how to debug, or what's going on, that would be great.  I've also noticed that when using the chrome developer tools, the crash brings down the entire tab, so the debugger / timeline recording of the events is also nuked.

[dstat-promote-rhel-newton-delorean-ha-17.log.gz](https://github.com/Dabz/dstat_graph/files/540043/dstat-promote-rhel-newton-delorean-ha-17.log.gz)

**Comment by halcyondude** [comment]
note using smaller time ranges with a file like what's attached works.

**Comment by Dabz** [comment]
Locally I was able to load & display this file. I suspect that you are currently encountering an issue with this file as the browser could requires a lot of resources to display a certain number of "dot".

To offload the memory usage, I included a quick aggregation system: meaning that instead of having one point per line, we could have one point that will contain the average of 5 lines, etc...

If you would like to increase/decrease granularity of the graph, granularity should be configurable in the header. 

The default rule is:

```
    if (lines.length > 7200) {
      settings.granularity = 15
    }  else if (lines.length > 3600) {
      settings.granularity = 5
    } else {
      settings.granularity = 1
    }

```

Could you try with the latest version and tell me if it improves the situation?

**Comment by halcyondude** [comment]
This works very well and resolved my issue.  thanks!
